### ISSUE TITLE
Banke - HPB - import

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#14]
https://github.com/osm-hr/data4import

Treba provjeriti i unijeti podatke koji fale

**Comment by hbogner** [comment]
Poslali si nam link na web sa listom poslovnica. Ponovno poslan mail sa objasnjenjem. c
c na nas data mail.

**Comment by hbogner** [comment]
Stigla nova tablica. Bit će danas/sutra na githubu.

**Comment by hbogner** [comment]
Poslali su samo bankomate...

**Comment by hbogner** [comment]
Zastarjelo? Rješavamo ili ignoriramo i zatvaramo?

**Comment by FikiCro** [comment]
Definitivno bi trebalo zatražiti novu tablicu i napraviti crosscheck.

**Comment by hbogner** [comment]
Zastarjelo
