### ISSUE TITLE
Benzinske - INA - import 

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#16]
Od ine smo dobili usmeno(telefonskim putem) dopuštenje korištenja podataka sa njihove stranice:
http://ina.hr/mapa/default.aspx
Te su rekli da oni svoje podatke šalju i na:
http://map.hak.hr/
te da se njima javimo za export podataka.
HAK nažalost traži pisanu potvrdu o dopuštenju, pa smo spali opet na prepisivanje sa weba.

**Comment by FikiCro** [comment]
Evo, sada imamo sređenu i INA-u uz Tifon i Crodux. Ima li kakvih novosti u vezi Petrola ili Lukoila?

**Comment by Janjko** [comment]
Svaka čast Fiki, ovo je velika stvar!

uto, 5. svi 2015. 23:48 FikiCro notifications@github.com je napisao:

**Comment by hbogner** [comment]
Svaka cast Fiki, majstore \o/
Od ostalih ni traga ni glasa :(

**Comment by hbogner** [comment]
Kako si unio sve zatvaram issue
