### ISSUE TITLE
Lista vrtića - import

### ISSUE THREAD

**Issue by mnalis** [osm-hr/osm-hr#18]
koristeći Janjkov OSM garden 
https://docs.google.com/spreadsheets/d/14jkoTkXSnkemNRStpJPi64lo8xPJLJufyKAqTWuKFO0/edit?usp=sharing

**Comment by hbogner** [comment]
Garden zastario, ali bit će uskoro novosti

**Comment by hbogner** [comment]
Imamo POI koji će se bolje iskoristiti:
https://github.com/osm-hr/osm-zipp-2018
