### ISSUE TITLE
Mapillary lokalizacija

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#21]
Započeta Mapillary lokalizacija:
https://github.com/osm-hr/mapillary_localization

**Comment by hbogner** [comment]
Dodao Stjepana, ponudio je pomoć oko prevođenja.

**Comment by streger** [comment]
Prevedeno.

**Comment by hbogner** [comment]
Pull request na mapillary repo, čekamo da prihvate i primjene.

**Comment by hbogner** [comment]
Nas prijevod primljen u mapillary repo
