### ISSUE TITLE
Ugasiti G+ community

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#27]
Stavljena je obavijest da ce se community ugasiti. Vidjeti hoce li se netko javiti, pa ugasiti za cca 2 tjedna ako se nitko ne javi.

**Comment by hbogner** [comment]
Hoćemo li samo staviti obavijest da je grupa zatvorena, ili da izbacim sve članove i pobrišem sve poruke?

**Comment by mnalis** [comment]
ako tamo nema sadrzaja koji nije dostupan nigdje drugdje, ja sam za
brisanje (nakon sto obavijest odstoji neko vrijeme)

**Comment by hbogner** [comment]
Obavijest stajala preko mjesec dana. Nitko se nije bunio. Danas pobrisano, izbaceni clanovi i ugaseno.
