### ISSUE TITLE
Novi izvor podataka pod open data licencom

### ISSUE THREAD

**Issue by dodobas** [osm-hr/osm-hr#3]
Danas sam saznao za ovo pa ako se nekom da više istražiti, vidio sam da postoje koordinate za škole, pa bi to valjalo provjeriti

http://data.zagreb.hr/dataset

**Comment by hbogner** [comment]
Mislim da je Matija vrtice ubacio u osm-garden. A ja sam skole push-ao u data4import.
Treba pratiti ako ce biti novih podataka.
