### ISSUE TITLE
Dodati generičko ime za posljedni daily export

### ISSUE THREAD

**Issue by dodobas** [osm-hr/osm-hr#35]
- uz 20150126-croatia.osm.pbf, treba dodati generičko ime `latest-data.pbf` ili nešto slično, koje će uvijek biti link na poslijednji dnevni backup

**Comment by hbogner** [comment]
Latest je u drugom folderu:
http://data.osm-hr.org/osm/

**Comment by hbogner** [comment]
Kreiran croatia-latest.osm.pbf

**Comment by hbogner** [comment]
Ovo u croatia folderu je arhiva. ovo u osm folderu je uvijek latest

**Comment by hbogner** [comment]
PS. Ovo je samo privremeno rješenje.
Za trajni link za zadnji export koristiti http://data.osm-hr.org/osm/croatia.osm.pbf

**Comment by hbogner** [comment]
Svaka država je dobila svoj posebni folder
