### ISSUE TITLE
Eggdrop irc logger

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#47]
Eggdrop se vise ne moze spojiti na irc server. Javlja gresku da nemoze naci server. Vidjeti jeli zbog promjena u resolv.conf ili nesto drugo?
Takodjer mozda posebni user za eggdrop? I njemu u cron job staviti provjeru jeli eggdrop aktivan.

**Comment by hbogner** [comment]
Sa standardnim postavkama javlja sljedeću grešku:
[21:23] Trying server #:6667
[21:24] Failed connect to # (DNS lookup failed)
[21:24] Trying server irc.freenode.net:6667

Kad pingam radi normalno,bar mislim da je ovo normalni odgovor :)
ping irc.freenode.net
PING chat.freenode.net (62.231.75.133) 56(84) bytes of data.
64 bytes from hobana.freenode.net (62.231.75.133): icmp_seq=1 ttl=54 time=83.8 ms
64 bytes from hobana.freenode.net (62.231.75.133): icmp_seq=2 ttl=54 time=84.6 ms
...
Kad umjesto irc.freenode.net stavim IP adresu normalno se spoji.
Što nije u redu s ovim???

Sad je trenutno rješeno sa IP adresom, ali treba vratiti irc.freenode.net i natjerati ga da radi kako treba.
U slučaju gašenja eggdrop procesa, neće se sam pokretati, dok ne rjesimo ovo.

**Comment by mnalis** [comment]
sto se tice DNSa, trebalo je zgasiti "loadmodule dns". Nagadjam da ga zbunjuje IPv6 u resolv.conf, jer pokusava slati upite na 0.0.0.0:0.

Napravio sam usera eggdrop, instalirao daemontools (i pokrenuo "service svscan start", valjda ce to automatski kod boota, tko ce znati s Ubuntu/upstartom), tako da se starta kao pravi user sa clean environmentom. Takodjer sam stavio /osm/eggdrop u git, da mozemo pratiti promjene. Sto se tice daemontoolsa:
- eggdrop se zaustavlja sa: `svc -d /service/eggdrop`
- a starta ponovo sa: `svc -u /service/eggdrop`
- ako treba samo restart, onda: `svc -t /service/eggdrop`
- ako proces umre sam od sebe, daemontoolsi ce ga automatski restartati.

To bi trebalo biti to, zatvaram.
