### ISSUE TITLE
tms.osm-hr.org server

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#51]
Server je pokrenut.
SSH port je promjenjen, root login onemogućen.
Treba pokrenuti munin-node i povezati ga na data server.
Treba pokrenuti awstats kao na data serveru.
Dražen i Matija dodani kao admini.

**Comment by mnalis** [comment]
munin dodan. awstats isto slozen, ali treba provjeriti sutra da li ce se automatski updateati podaci za "26 Jun 2015". dodana smartcard & etckeeper magija :)

**Comment by hbogner** [comment]
Opet ista greska sa awstatsom, nije procesirao stari log, iako sam ga migrirao.

**Comment by mnalis** [comment]
hm, jesi li ih zaista migrirao? na _tms.osm-hr.org_, u `/var/lib/awstats` ne vidim te datafileove kao sto sam ih vidio na _data.osm-hr.org_?

**Comment by hbogner** [comment]
apache log sam migrirao

**Comment by mnalis** [comment]
from http://stackoverflow.com/questions/13832701/how-do-i-get-awstats-to-analyze-old-log-files

``` shell
cd /var/log/apache2
mkdir w
cp tms-access.log* w
cd w
gunzip *gz
rm /var/lib/awstats/* # backup first!
sudo -u www-data awstats -update -config="tms.osm-hr.org" -LogFile="/usr/share/awstats/tools/logresolvemerge.pl /var/log/apache2/w/tms-access.log* |"
rm -rf /var/log/apache2/w
```

to je rekreiralo datafiles iz apache logova, a onda možemo rekreirati HTML kao i na data.osm-hr.org:

``` shell
cd /root/awstats_rebuild
./runme.sh
```

sada bi trebalo biti riješeno (hopefully)...
