### ISSUE TITLE
problemi sa net konekcijom

### ISSUE THREAD

**Issue by hbogner** [osm-hr/osm-hr#53]
Problemi sa replikacijom. Nemogu povuci ni update/upgrade a ni sama replikacija neradi.

**Comment by hbogner** [comment]
Problem rijesen. Bar za sad.

**Comment by mnalis** [comment]
problem je bio (i još je, samo što ga sa kludgem ignoriramo) što se nešto ružno dogodilo sa IPv6 connectivityem. (v. issue #54)

**Comment by hbogner** [comment]
Problem je sa IPv6 u resolv.conf. Dok god su oni prisutni neradi kako treba.

**Comment by hbogner** [comment]
Koliko vidim ovako iz daleka preko mobitela opet neradi ipv4!

**Comment by hbogner** [comment]
divlji fix
dodao 

> nameserver 8.8.8.8
> nameserver 8.8.4.4

u  /etc/resolvconf/resolv.conf.d/head
tako da pri sljedecem "resolvconf -u" nećemo izgubiti ipv4

**Comment by mnalis** [comment]
to je skroz ok fix (iako je upitno uopće da nam treba zli Ubuntuov resolvconf umjesto lijepog statičkog /etc/resolv.conf).

**Comment by hbogner** [comment]
To sam te i mislio pitat, hocemo ga maknut i sami ga rucno upisat.
Jucer mi nije radio ni Carnetov ipv4, samo ovaj google.

**Comment by mnalis** [comment]
mislio sam, ali Ubuntu dependa na njega preko ubuntu-minimal, pa da se ne razlete dalje stvari.
Vjerojatno je čišće rješenje specificirati DNS servere u /etc/network/interfaces preko dns-nameservers direktive (nisam dirao zasad).

Cudno za CARNetov IPv4 DNS, to je trebalo raditi (ili uz ovo sa IPv6 imamo jos neke probleme!)
A koji je bio koristio CARNetov IPv4 DNS (ne vidim ga u resolv.conf)?
