### ISSUE TITLE
Add TMS to editors?

### ISSUE THREAD

**Issue by grischard** [osm-hr/osm-hr#60]
Hi Croatian community,

Your TMS isn't included in the Editor Layer Index, which means it has to be added as a custom layer to iD.

Would it be ok to add it?

Would you please have a polygon that shows the coverage of the different layers?

Is it possible to georeference old maps to add to the coverage?

Thanks!

**Comment by hbogner** [comment]
Hi Guillaume

Yes our TMS isn't included in Editor Layer Index because we didn't think of it as so important.
But recently I acquired imagery for few new layers and updates for some current layers, just need to process and upload them first.
When we publish new layers it would be great to add them.
We could create a polygon for those layers.

What do you mean with georeference old maps? 
Our country does not allow use and distribution of state maps.
If you mean those topographic, maps, they are US made and made freely available, and iIhave some updates for them.

Regards

**Comment by grischard** [comment]
Hey Hrvoje,

I saw that the Serbian community likes to trace from it, and even has a fork of iD that includes your TMS. I'm sure that many other people who could benefit from the layer don't know about it. Definitely happy to add them whenever you want - ping me here or on irc.

Yes, I did mean the US maps of former Yugoslavia. There are some on http://legacy.lib.utexas.edu/maps/topo/former_yugoslavia/

**Comment by hbogner** [comment]
Will do that.
Let me just first process 3 imagery sources and create TMS layers for them and upload them.
There is also an update for those topo maps of former Yugoslavia  TMS layer.
I'll fork the Editor Layer Index repo, try to do it by myself and create a pull request. It's this one: https://github.com/osmlab/editor-layer-index ?

**Comment by hbogner** [comment]
Hey Guillaume

Here is my first attempt at Orbview layer
https://github.com/osm-hr/editor-layer-index/commit/349c228d993cd012726e4fd7aa57d12270b15f73
I had troubles with multiple polygons in geojson, but here is it in osm file.
Former Yugosavia also has multiple polygons.
Other layers will be single areas.

**Comment by hbogner** [comment]
Here is US Topo layer:
https://github.com/osm-hr/editor-layer-index/commit/1dcea6421bff229a02be4cc04b4cd4034deff96d

**Comment by hbogner** [comment]
Here is the list of TODO
- [x] Knin 2007 Aerial imagery
- [x] Zagreb 2012 Aerial imagery
- [x] Zagreb 2018 Aerial imagery
- [x] US Topo
- [x] Orbview3
- [x] DGU Topo 200
- [x] DGU Topo 100
- [x] DGU Topo 25
- [x] DGU Topo 25-novi
- [x] DGU HOK
- [x] DGU Aerial 2011
- [x] DGU Aerial 2014-2016
- [x] DGU Aerial 2017
- [x] DGU Aerial 2018

**Comment by hbogner** [comment]
Almost done! Zagreb and commercial are up to me to process and publish first.
Add RGI or not?
Discussion on mailing list: https://lists.openstreetmap.org/pipermail/talk-hr/2019-October/002694.html

**Comment by grischard** [comment]
Look at that beautiful layer density on https://osmlab.github.io/editor-layer-index/ :)

If you want, you can simplify your polygons by just cutting a straight line through the Adriatic. As long as you don't reach the Italian coast, it's not like anyone is going to be mapping there.

**Comment by hbogner** [comment]
Few more will come, and it be more dense :)
They became active in iD yesterday :)

**Comment by hbogner** [comment]
https://osm-hr.org/2019/10/31/hrvatske-podloge-od-sad-dostupne-kao-standardni-slojevi-u-editorima/ :)

**Comment by hbogner** [comment]
All currently available are in editors. New will be added as they are processed.
