### ISSUE TITLE
hrvatske pošte - mass import

### ISSUE THREAD

**Issue by mnalis** [osm-hr/osm-hr#9]
Imamo dozvolu Hrvatske Poste da za OSM koristimo sve podatke dostupne na
http://www.posta.hr/karta-postanskih-ureda

pa treba složiti da se vidi što imamo a što ne (Janjko scripta za google docs?)

**Comment by hbogner** [comment]
Zastarjelo? Rješavamo ili ignoriramo i zatvaramo?

**Comment by hbogner** [comment]
zastarjelo
